-- Auto-generated by Rakkib Step 4

-- n8n
DO $rakkib_1$BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = $rakkib$n8n$rakkib$) THEN
        CREATE ROLE n8n WITH LOGIN PASSWORD $rakkib$n8n-db-pass$rakkib$;
    ELSE
        ALTER ROLE n8n WITH PASSWORD $rakkib$n8n-db-pass$rakkib$;
    END IF;
END$rakkib_1$;
SELECT 'CREATE DATABASE n8n_db OWNER n8n' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = $rakkib$n8n_db$rakkib$) \gexec

-- NocoDB
DO $rakkib_1$BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = $rakkib$nocodb$rakkib$) THEN
        CREATE ROLE nocodb WITH LOGIN PASSWORD $rakkib$nocodb-db-pass$rakkib$;
    ELSE
        ALTER ROLE nocodb WITH PASSWORD $rakkib$nocodb-db-pass$rakkib$;
    END IF;
END$rakkib_1$;
SELECT 'CREATE DATABASE nocodb_db OWNER nocodb' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = $rakkib$nocodb_db$rakkib$) \gexec
