"""Step 4 — PostgreSQL.

Deploy PostgreSQL and create one database/user pair per selected service.
"""

from __future__ import annotations

import os
from pathlib import Path

from rakkib.docker import DockerError, create_network, docker_run
from rakkib.postgres_sql import postgres_identifier, postgres_literal
from rakkib.render import render_file, render_text
from rakkib.secret_utils import ensure_secrets
from rakkib.state import State
from rakkib.steps import VerificationResult, load_service_registry, selected_service_defs
from rakkib.tui import progress_spinner, progress_wait
from rakkib.util import RAKKIB_DATA_DIR


def _repo_dir() -> Path:
    """Return the package data directory (contains ``templates/``)."""
    return RAKKIB_DATA_DIR


def _parse_env(text: str) -> dict[str, str]:
    """Parse KEY=VALUE lines from an env-style string."""
    result: dict[str, str] = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            key, value = line.split("=", 1)
            result[key.strip()] = value.strip()
    return result


def _merge_env(candidate_text: str, existing_path: Path) -> str:
    """Return *candidate_text* with any existing keys from *existing_path* preserved."""
    if not existing_path.exists():
        return candidate_text

    existing = _parse_env(existing_path.read_text())
    lines: list[str] = []
    for line in candidate_text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            lines.append(line)
            continue
        if "=" in stripped:
            key = stripped.split("=", 1)[0].strip()
            if key in existing:
                lines.append(f"{key}={existing[key]}")
            else:
                lines.append(line)
        else:
            lines.append(line)
    return "\n".join(lines) + "\n"


def _generate_init_sql(state: State) -> str:
    """Generate init-services.sql based on selected services."""
    lines = ["-- Auto-generated by Rakkib Step 4", ""]
    secrets = state.get("secrets.values", {}) or {}
    services = selected_service_defs(state, load_service_registry())

    def _password_for(svc_id: str, key: str) -> str:
        value = secrets.get(key)
        if value is None:
            value = state.get(key)
        if value is None:
            raise RuntimeError(
                f"Postgres provisioning requires secret '{key}' for service '{svc_id}'. "
                "Set the password in state or re-run secret generation before Step 4."
            )
        return str(value)

    def _add_service(name: str, role: str, password: str, db_name: str | None = None) -> None:
        role = postgres_identifier(role, field=f"postgres role for service {name}")
        db = postgres_identifier(db_name or role, field=f"postgres database for service {name}")
        role_literal = postgres_literal(role)
        db_literal = postgres_literal(db)
        password_literal = postgres_literal(password)
        block = "\n".join(
            [
                "BEGIN",
                f"    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = {role_literal}) THEN",
                f"        CREATE ROLE {role} WITH LOGIN PASSWORD {password_literal};",
                "    ELSE",
                f"        ALTER ROLE {role} WITH PASSWORD {password_literal};",
                "    END IF;",
                "END",
            ]
        )
        lines.extend(
            [
                f"-- {name}",
                f"DO {postgres_literal(block)};",
                f"SELECT 'CREATE DATABASE {db} OWNER {role}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = {db_literal}) \\gexec",
                "",
            ]
        )

    for svc in services:
        postgres = svc.get("postgres") or {}
        if not postgres:
            continue
        role = postgres.get("role", svc["id"])
        _add_service(
            postgres.get("display_name", svc["id"]),
            role,
            _password_for(svc["id"], postgres["password_key"]),
            postgres.get("db", role),
        )

    return "\n".join(lines)


def _permission_denied_hint(stderr: str, data_root: Path | None) -> str | None:
    lowered = stderr.lower()
    if "global/pg_filenode.map" not in lowered or "permission denied" not in lowered:
        return None

    data_dir = data_root / "data" / "postgres" / "data" if data_root else Path("<data_root>/data/postgres/data")
    return (
        f"Postgres cannot read its mounted data directory ({data_dir}). "
        "Repair ownership on the target server, then restart Postgres: "
        f"`sudo chown -R 999:999 {data_dir} && sudo chmod -R u+rwX,go-rwx {data_dir} && docker restart postgres`."
    )


def _apply_sql(sql: str, data_root: Path | None = None) -> None:
    """Execute *sql* directly inside the postgres container via psql."""
    result = docker_run(
        ["exec", "-i", "postgres", "psql", "-h", "127.0.0.1", "-U", "postgres"],
        input=sql,
        check=False,
    )
    if result.returncode != 0:
        stderr = result.stderr.strip()
        hint = _permission_denied_hint(stderr, data_root)
        detail = f"{stderr}\n\n{hint}" if hint else stderr
        raise RuntimeError(
            f"psql failed (rc={result.returncode}):\n{detail}"
        )


def _wait_for_healthy(container: str = "postgres", timeout: int = 60) -> None:
    """Poll Docker health status until *container* is healthy."""
    def poll() -> bool:
        result = docker_run(
            ["inspect", "--format", "{{.State.Health.Status}}", container],
            check=False,
        )
        status = result.stdout.strip()
        if status == "healthy":
            return True

        # Some templates intentionally omit a Docker healthcheck.
        # In that case, fall back to pg_isready so Step 4 still works.
        if status in {"", "<no value>"} or result.returncode != 0:
            ready = docker_run(
                ["exec", container, "pg_isready", "-h", "127.0.0.1", "-U", "postgres"],
                check=False,
            )
            return ready.returncode == 0

        return False

    if progress_wait(f"Waiting for {container} health...", timeout, poll):
        return
    raise RuntimeError(f"Postgres did not become healthy within {timeout}s")


def run(state: State) -> None:
    data_root = state.data_root
    postgres_dir = data_root / "docker" / "postgres"
    init_dir = postgres_dir / "init-scripts"
    init_dir.mkdir(parents=True, exist_ok=True)

    log_path = data_root / "logs" / "postgres.log"
    log_path.parent.mkdir(parents=True, exist_ok=True)

    # 1. Generate missing secrets if configured to do so.
    if state.get("secrets.mode") == "generate":
        ensure_secrets(state)

    repo = _repo_dir()

    # 2. Render .env.example candidate and merge with existing .env.
    env_candidate = render_text(
        (repo / "templates" / "docker" / "postgres" / ".env.example").read_text(),
        state,
    )
    env_path = postgres_dir / ".env"
    merged = _merge_env(env_candidate, env_path)
    env_path.write_text(merged)
    # Ensure restrictive permissions.
    os.chmod(env_path, 0o600)

    # 3. Generate init SQL.
    sql = _generate_init_sql(state)
    sql_path = init_dir / "init-services.sql"
    sql_path.write_text(sql)
    os.chmod(sql_path, 0o600)

    # 4. Render docker-compose.yml.
    render_file(
        repo / "templates" / "docker" / "postgres" / "docker-compose.yml.tmpl",
        postgres_dir / "docker-compose.yml",
        state,
    )

    # 5. Start PostgreSQL.
    create_network(str(state.get("docker_net", "caddy_net")))
    try:
        docker_run(["compose", "up", "-d"], cwd=postgres_dir, progress_message="Starting PostgreSQL...")
    except DockerError as exc:
        raise RuntimeError(f"docker compose up failed: {exc}") from exc

    # 6. Wait for healthy.
    _wait_for_healthy()

    # 7. Apply roles/databases directly so passwords are always in sync.
    #    (The init-scripts directory is only executed by postgres on first boot;
    #    re-runs would leave stale passwords without this direct apply.)
    with progress_spinner("Applying Postgres roles and databases..."):
        _apply_sql(sql, data_root=data_root)

    log_path.write_text("postgres step completed\n")


def verify(state: State) -> VerificationResult:
    # Container running?
    ps = docker_run(["ps", "--filter", "name=^postgres$", "--format", "{{.Names}}"], check=False)
    if "postgres" not in ps.stdout:
        return VerificationResult.failure("postgres", "Postgres container is not running")

    # pg_isready?
    ready = docker_run(
        ["exec", "postgres", "pg_isready", "-h", "127.0.0.1", "-U", "postgres"],
        check=False,
    )
    if ready.returncode != 0:
        return VerificationResult.failure("postgres", f"pg_isready failed: {ready.stderr.strip()}")

    return VerificationResult.success("postgres", "Postgres is running and accepting connections")
